use_frameworks!

target 'YDQDemo_Example' do
  pod 'YDQDemo', :path => '../'

  target 'YDQDemo_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
